//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentManagement_List.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentManagement_List.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Accessed a system file.
        ///System files are excluded from the search.
        ///Check the Log folder for excluded folders.
        ///Log folder : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgAccessSystemFile {
            get {
                return ResourceManager.GetString("msgAccessSystemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgAuthor {
            get {
                return ResourceManager.GetString("msgAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already set, do you want to change it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgChangeSetting {
            get {
                return ResourceManager.GetString("msgChangeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The narrowing condition has been specified.
        ///The conditions will be cleared, but are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCheckClearCondition {
            get {
                return ResourceManager.GetString("msgCheckClearCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Classified に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgClassified {
            get {
                return ResourceManager.GetString("msgClassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)言語設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonCulture {
            get {
                return ResourceManager.GetString("msgCommonCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)標準機密区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonDefaultSecrecy {
            get {
                return ResourceManager.GetString("msgCommonDefaultSecrecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonFileNothing {
            get {
                return ResourceManager.GetString("msgCommonFileNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)最終版 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonFinal {
            get {
                return ResourceManager.GetString("msgCommonFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)事業所コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonOfficeCode {
            get {
                return ResourceManager.GetString("msgCommonOfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のサーバーパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSABListLocalPath {
            get {
                return ResourceManager.GetString("msgCommonSABListLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のローカルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSABListServerPath {
            get {
                return ResourceManager.GetString("msgCommonSABListServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)セキュアフォルダリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSecureFolder {
            get {
                return ResourceManager.GetString("msgCommonSecureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルで設定していない項目があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSettingNothing {
            get {
                return ResourceManager.GetString("msgCommonSettingNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)zip一時解凍先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonTempPath {
            get {
                return ResourceManager.GetString("msgCommonTempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgConfirmation {
            get {
                return ResourceManager.GetString("msgConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Created date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCreateDate {
            get {
                return ResourceManager.GetString("msgCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect password-protected zip  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgDetectPassword {
            get {
                return ResourceManager.GetString("msgDetectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Document classification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgDocumentClass {
            get {
                return ResourceManager.GetString("msgDocumentClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you add it by drag and drop, it will not match the search key. Is it okay? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgDragAndDrop {
            get {
                return ResourceManager.GetString("msgDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrorArgumentOutOfRange {
            get {
                return ResourceManager.GetString("msgErrorArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrorFileOpen {
            get {
                return ResourceManager.GetString("msgErrorFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrorFolderOpen {
            get {
                return ResourceManager.GetString("msgErrorFolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel File(*.xlsx)|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgExcelfile {
            get {
                return ResourceManager.GetString("msgExcelfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelExport_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgExportExcelDefault {
            get {
                return ResourceManager.GetString("msgExportExcelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exported an Excel file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgExportExcelFile {
            get {
                return ResourceManager.GetString("msgExportExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get file information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedFileInfo {
            get {
                return ResourceManager.GetString("msgFailedFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open GCP secrecy documents list (SA secrecy). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedOpenGCPdocument {
            get {
                return ResourceManager.GetString("msgFailedOpenGCPdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read common setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadCommonFile {
            get {
                return ResourceManager.GetString("msgFailedReadCommonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read CSV file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadCsvFile {
            get {
                return ResourceManager.GetString("msgFailedReadCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read document path in common setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadDocumentPath {
            get {
                return ResourceManager.GetString("msgFailedReadDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are files whose properties could not be read.
        ///Check the document classification item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadPropertyFile {
            get {
                return ResourceManager.GetString("msgFailedReadPropertyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read user setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadUserSetting {
            get {
                return ResourceManager.GetString("msgFailedReadUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File search failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedSearchFile {
            get {
                return ResourceManager.GetString("msgFailedSearchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   files could not be set.
        ///Check the document classification item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedSettingFile {
            get {
                return ResourceManager.GetString("msgFailedSettingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write the Excel file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedWriteExcelFile {
            get {
                return ResourceManager.GetString("msgFailedWriteExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write user setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedWriteUserSetting {
            get {
                return ResourceManager.GetString("msgFailedWriteUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   over.
        ///Do you want to continue processing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFileContinueProcess {
            get {
                return ResourceManager.GetString("msgFileContinueProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please search again with less than 100,000 files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFileLessHundredThousand {
            get {
                return ResourceManager.GetString("msgFileLessHundredThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFileName {
            get {
                return ResourceManager.GetString("msgFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number of files exceeds 100,000. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFileOverHundredThousand {
            get {
                return ResourceManager.GetString("msgFileOverHundredThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFilePath {
            get {
                return ResourceManager.GetString("msgFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target file is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFileTarget {
            get {
                return ResourceManager.GetString("msgFileTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last updated by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgLastUpdate {
            get {
                return ResourceManager.GetString("msgLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotExistFolder {
            get {
                return ResourceManager.GetString("msgNotExistFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotFileExist {
            get {
                return ResourceManager.GetString("msgNotFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   does not exist in the secure folder and therefore cancels the process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotSecureFolder {
            get {
                return ResourceManager.GetString("msgNotSecureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgOpenFile {
            get {
                return ResourceManager.GetString("msgOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It may take a long time to search, but are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSearchLongTime {
            get {
                return ResourceManager.GetString("msgSearchLongTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the data to change. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectData {
            get {
                return ResourceManager.GetString("msgSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the save destination file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectFile {
            get {
                return ResourceManager.GetString("msgSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectFolder {
            get {
                return ResourceManager.GetString("msgSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The upper folder is specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectFolderUpper {
            get {
                return ResourceManager.GetString("msgSelectFolderUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a folder to search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectSearchFolder {
            get {
                return ResourceManager.GetString("msgSelectSearchFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you put a stamp on an Office file, it may take some time to process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStampOfficeFile {
            get {
                return ResourceManager.GetString("msgStampOfficeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Obtaining file information {0} / {1}number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStatusInfo {
            get {
                return ResourceManager.GetString("msgStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File search target file {0}number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStatusSearch {
            get {
                return ResourceManager.GetString("msgStatusSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting file information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStatusSetting {
            get {
                return ResourceManager.GetString("msgStatusSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storage period に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStoragePeriod {
            get {
                return ResourceManager.GetString("msgStoragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Storage period (years) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgStoragePeriodYear {
            get {
                return ResourceManager.GetString("msgStoragePeriodYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgUpdateDate {
            get {
                return ResourceManager.GetString("msgUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)表示切替ボタン押下処理でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgViewChangeError {
            get {
                return ResourceManager.GetString("msgViewChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   zip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZip {
            get {
                return ResourceManager.GetString("msgZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipDecompress {
            get {
                return ResourceManager.GetString("msgZipDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZIP File(*.zip)|*.zip|All File(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipFile {
            get {
                return ResourceManager.GetString("msgZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)ファイルエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipFileError {
            get {
                return ResourceManager.GetString("msgZipFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   → に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipFormatContent {
            get {
                return ResourceManager.GetString("msgZipFormatContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   〇 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipFormatFile {
            get {
                return ResourceManager.GetString("msgZipFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipFormatNot {
            get {
                return ResourceManager.GetString("msgZipFormatNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipListDelete {
            get {
                return ResourceManager.GetString("msgZipListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)パスワード付き に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgZipPasswordError {
            get {
                return ResourceManager.GetString("msgZipPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampA {
            get {
                object obj = ResourceManager.GetObject("StampA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampB {
            get {
                object obj = ResourceManager.GetObject("StampB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StampDisplay_OFF {
            get {
                return ResourceManager.GetString("StampDisplay_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StampDisplay_ON {
            get {
                return ResourceManager.GetString("StampDisplay_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap StampS {
            get {
                object obj = ResourceManager.GetObject("StampS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
